### ISSUE TITLE
Ready for SQL users

### ISSUE THREAD

**Issue by machow** [machow/siuba#16]
As a SQL user, I can

- [ ] tell when a function will work with SQL
- [ ] easily add function translations to siuba
- [x] trust that the tool is thoroughly tested

depends on #17, #18

**Comment by machow** [comment]
replacing with individual issues
